Update Git workflow
BonnierGaming/guides pull request #9
Opened 2017-03-01 11:05 UTC by pietro909

Several things have changed in the last 10 months:

* we use Jira rather than Redmine
* GitLab is used for reviewing and merging
* the main branch is now `next`

2017-03-07 10:54 UTC, pmodin requested changes
Also, `s/jira/JIRA/gi`

Good thing you went through this document, let's discuss further.

2017-03-07 10:54 UTC, pmodin commented on process/merge_requests/README.md
> +9. Set label "Ready for review".
This is on a per project basis. The projects I mostly work in, for example, we consider all MRs as ready for review unless labeled as WIP.

2017-03-07 10:54 UTC, pmodin commented on process/merge_requests/README.md
> +10. Assign it to another developer.
This is also on a per project basis

2017-03-07 10:54 UTC, pmodin commented on process/merge_requests/README.md
> +with the name `Ready for release` will be applied, indicating that the branch is
This is also a per-project convention, nowadays. Good find.

2017-03-12 22:22 UTC, pietro909 commented
I think that at this point we need to split the documentation per project, keeping the common procedures in the these documents.

2017-03-12 22:33 UTC, pmodin commented
Agreed, let's have a workshop 😃

2017-03-31 07:57 UTC, miono commented
why am i still able to comment here??? remove me.

2017-03-31 07:59 UTC, jeltz commented
While removing Markus, you could also remove me as well.

2017-04-04 09:05 UTC, pmodin commented
@miono @jeltz It's a public repository, if you don't want to be notified you can unfollow it 😸

2017-04-04 12:40 UTC, pietro909 commented on style/git/README.md
> +1. Branch `next` contains the latest stable release
still `master` branch for deployment

2017-04-21 14:57 UTC, pietro909 commented
@pmodin it would be nice close this PR at the latest by May 1st since later I might not have access to this repo anymore 😸

2026-05-19 17:42 UTC, closed without merging

2026-05-19 17:48 UTC, miono commented
Oh nooo! Why close so prematurely?!

2026-05-19 17:51 UTC, jeltz commented
Yeah, that if there is still any interest?